vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn = 'yes'
vim.opt.updatetime = 300
vim.opt.wrap = false
vim.opt.mouse = 'a'
vim.opt.encoding = 'utf-8'
vim.opt.cursorline = true
vim.opt.swapfile = false
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.wildmenu = true
vim.opt.hlsearch = true
vim.opt.smartcase = true
vim.opt.showcmd = true
vim.opt.showmode = true
vim.opt.showmatch = true
vim.opt.scrolloff = 4
vim.opt.history = 1000
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.expandtab = true
vim.opt.list = true
vim.opt.undofile = true
-- vim.opt.undodir = cache_dir .. 'undo/'
-- vim.opt.backupdir = cache_dir .. 'backup/'
vim.opt.listchars = 'tab:»·,nbsp:+,trail:·,extends:→,precedes:←'
vim.opt.colorcolumn = '80'
vim.g.mapleader = ' '
vim.g.python3_host_prog='~/.anaconda3/bin'
